name: Tests

on:
  push:
    branches:
      - master
      - v2/provider-health
  pull_request:

jobs:
  unit-tests:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Run unit tests
        run: python -m unittest discover -s tests -v
